services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: inventory_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: pavelfit/inventory-image:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: secretpassword
      DB_NAME: inventory_db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # --- НАШ НОВЫЙ РОБОТ CD ---
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  pgdata:
