name: Мой первый CI/CD Конвейер

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    steps:
      - name: Шаг 1. Скачиваем код
        uses: actions/checkout@v4

      # ----------------------------------------------------
      # ВОТ ЗДЕСЬ МЫ УКАЗЫВАЕМ, В КАКОЙ ХАБ ИДТИ (АВТОРИЗАЦИЯ)
      # ----------------------------------------------------
      - name: Шаг 2. Авторизация в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ----------------------------------------------------
      # ВОТ ЗДЕСЬ МЫ УКАЗЫВАЕМ, КУДА СОХРАНЯТЬ (ОТПРАВКА)
      # ----------------------------------------------------
      - name: Шаг 3. Сборка и отправка
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # Эта команда говорит: "Отправь в интернет!"
          
          # А вот здесь мы формируем ту самую ссылку для docker pull!
          # Робот подставит твой логин из секретов и приклеит к нему название:
          tags: ${{ secrets.DOCKER_USERNAME }}/inventory-image:latest
